<?php
// $Id: dirtyforms.install,v 1.1.2.1 2009/03/30 01:28:12 markuspetrux Exp $

/**
 * @file
 * Module installation/uninstallation hooks.
 */

/**
 * Implementation of hook_uninstall().
 */
function dirtyforms_uninstall() {
  // Delete all module variables and then clear the variables cache.
  db_query("DELETE FROM {variable} WHERE name LIKE 'dirtyforms\_%'");
  cache_clear_all('variables', 'cache');
}
